_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 24
                - 55
            "4": 3.13.2
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
